@echo off
echo Cleaning up FolioFinds project...

echo Stopping any running Node.js processes...
taskkill /f /im node.exe 2>nul

echo Removing .next directory...
rmdir /s /q .next 2>nul

echo Removing node_modules...
rmdir /s /q node_modules 2>nul

echo Removing package-lock.json...
del package-lock.json 2>nul

echo Installing dependencies...
npm install

echo Building project...
npm run build

echo Starting development server...
npm run dev

pause 